name: Caching Python requirements
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache Python Packages
        id: cache-python
        steps:
          - uses: actions/setup-python@v5
            with:
              python-version: '3.9'
              cache: 'pip' # caching pip dependencies
          - run: pip install -r requirements.txt

      - if: ${{ steps.cache-python.outputs.cache-hit != 'true' }}
        name: Install pip packages
        continue-on-error: true
        run: pip install -r ./requirements.txt

      - name: List pip packages
        run: echo "Cache Hit Status - ${{ steps.cache-python.outputs.cache-hit }}"; pip list package